### PR TITLE
Adding tickInterval as in HighCharts

### LINKED ISSUE #190: [Axis] Add tickinterval capability
Same as Highcharts http://jsfiddle.net/gh/get/jquery/2/highcharts/highcharts/tree/master/samples/highcharts/xaxis/tickinterval-5/

### PR DESCRIPTION
**Pull request by shprink**
Closes #190 

Possibilities:

* tickValues: Array of Number `[5, 10, 15]` Here displays only 3 ticks
* tickInterval: Number  `5` will display a tick every 5
* ticks: Number `5` Will force 5 ticks to be displayed (mode auto)

### CODE REVIEW

**Comment by rrag** [comment]
How are you doing this?

> ticks: Number 5 Will force 5 ticks to be displayed (mode auto)

does not look like you are forcing only 5 ticks

**Comment by shprink** [comment]
`ticks` is a props that already exists. Have not touched it. Just listing all the possibilities to display ticks

**Comment by shprink** [comment]
I added on `tickInterval`

**Comment by rrag** [comment]
got, it `ticks` will actually not force, it is just a guidance, 

see https://github.com/d3/d3-scale#continuous_ticks

got confused with the comment about force.

This looks good

**Comment by shprink** [comment]
yes you are right, sometimes it is less, sometimes more.

**Pull request merged**
