### PR TITLE
Large performance improvement for wickNest.forEach.outer

### PR DESCRIPTION
**Pull request by stevesouth**
From around 5ms to 1ms on Android (Nexus 6p).

Please double check you are happy with the rendering. As I am using a different canvas method the line thickness can look slightly different.

### CODE REVIEW

**Comment by rrag** [comment]
the line thinkness will be an issue, I get the your idea thoug, let me dig into this more, and see what I can do.

**Comment by stevesouth** [comment]
Sure. Essentially it seems fillRect and strokeRect are far faster than beginPath / moveTo / lineTo / stroke so its best to use them wherever possible.

**Comment by rrag** [comment]
implemented your ideas in `next`. closing the pr.

Thinking of implementing touch move without react event system, just like pan.

Thank you for these ideas.

**Comment by rrag** [comment]
if you have time use the latest `next` branch, just pushed s change to `BarSeries.jsx` which saves ~5ms per animation frame

For the [macd example](http://rrag.github.io/react-stockcharts-next/documentation.html#/macd) on my computer, an animationframe which was taking 25.6ms now takes 16.1ms as there are 2 bar charts (1 for volume and 1 for the macd bar, so savings of ~5 ms each). Haven't tested on mobile yet, must be lot better there. This is getting just too exciting.

**Comment by stevesouth** [comment]
Great. I agree with the touch move change, that would make a big difference.

Also, wherever you are calling requestAnimationFrame, you should check you aren't calling it more than once per frame as that is causing unnecessary work. Most request animation frame calls should look something like.

if (!waitingForPanFrame) {
 waitingForPanFrame = true;
 requestAnimationFrame(function() {
  waitingForPanFrame = false;
  doPanningStuff();
 });
}

**Comment by rrag** [comment]
that is a great idea. this one improved the perf a lot. from about 35 fps to 55 fps

Also implemented the touchmove using d3, pinchzoom is broken now, will fix later

**Pull request closed without merging**
