### PR TITLE
Added % change to OHLCTooltip

### PR DESCRIPTION
**Pull request by piotryordanov**
OHLCTooltip now displays %change next to volume!

### CODE REVIEW

**Comment by rrag** [comment]
Thank you

```
percent = percentFormat((item.close - item.open) / item.open)
```

that is not percent change, it is 
```
percent = percentFormat((item.close - item.prevClose) / item.prevClose)
```
if you populate data with `prevClose` then you can change the `defaultProps` like so

```diff
accessor: (d) = > {
    return {
        date: d.date,
        open: d.open,
        high: d.high,
        low: d.low,
        close: d.close,
+       prevClose: d.prevClose
        volume: d.volume
    };
},
```

Any case I do not like adding another datapoint to the `OHLCTooltip` It should rather be `OHLCTooltipV2` and then potentially extract functions which can be reused between the two

**Comment by piotryordanov** [comment]
Yes, I agree that this looks more of a hack.
The thing that does bother me is the fact that I can't customize the looks and feel of the stuff displayed. Would it make sense if I worked a bit more on this so as to have the tooltip receive children as props, OR display the default as it is currently?

**Comment by rrag** [comment]
> receive children as props

I like that idea, can we chat on gitter more? I want to understand what you are thinking here

**Comment by piotryordanov** [comment]
Yes, where do I login?

**Comment by rrag** [comment]
https://gitter.im/rrag/react-stockcharts

**Pull request closed without merging**
