### PR TITLE
Triangular Moving Average indicator (TRIMA)

### PR DESCRIPTION
**Pull request by mgeri**
Triangular Moving Average (TRIMA)
The Triangular Moving Average can be used like any other Moving Average, to obtain a smoother representation of the underlying data. It is important to note that the Triangular Moving Average is typically much smoother than other moving averages.

### CODE REVIEW

**Comment by rrag** [comment]
Thank you for this. I have sent you an invite to be a collaborator for the repo, please accept.

I have been thinking of moving all the algorithms and indicators to a separate module, also try to make building a chart simpler, with a config object, something like

```
var chart = buildChart(config)
...
<div>{chart}</div>
```

I would like to hear your opinion and any suggestions you have, we can chat on gitter.

**Comment by mgeri** [comment]
Hi Ragu,

thank you very much for your invite. I'm glad to accept it.
It's the first time I'm collaborating to a github project and as I told you
in my previous mail I'm quite new to ReactJS's world... I will try to
contribute in my spare time as mush as I can and with caution to avoid
mistakes (please, be patient for my questions :-) )

I agree with you... there could be many indicators and it would be better
to have them well organised as external module... Do you already have any
idea on how organise it or from which to start thinking?

I also agree that would be easier to build it using a js config object...
for me (I know something about javascript and very little of ReactJS) it
was not so easy to understand how to configure it at the beginning.

I have never used gittet... I will look at it next few days (so we can use
it if needed).

Cheers,
Marco


2017-01-08 1:07 GMT+01:00 Ragu Ramaswamy <notifications@github.com>:

**Comment by rrag** [comment]
is `TRIMA` the right name? can we call it `TMA` ?

**Comment by mgeri** [comment]
Hi Ragu,

When I started to write it, I took the name from TA-lib (
http://ta-lib.org/function.html) which is one of the well known open source
technical analysis library.

Looking around I found it called TRIMA and others TMA... so yes, we can
call it TMA if we prefer to take its name shorter (in this case probably
would be better rename also file name). Let me know... :-)

Cheers
Marco






2017-01-12 12:44 GMT+01:00 Ragu Ramaswamy <notifications@github.com>:

**Comment by rrag** [comment]
I changed it, `trima` to `tma`, also added a sar indicator, and updates the docs

http://rrag.github.io/react-stockcharts-next/documentation.html#/moving_average
http://rrag.github.io/react-stockcharts-next/documentation.html#/sar

will publish a new version after addressing a couple of issues

**Pull request merged**
