### PR TITLE
add AutoCAD-like hotkeys for trend-line drawing

### PR DESCRIPTION
**Pull request by WaiSiuKei**
added hotkeys for drawing and support 3 kinds of line:
XLINE - Lines that extend to infinity;
RAY - Line that starts at a point and continues to infinity;
LINE - Straight line segments;

and the hotkeys are:
X - XLINE
R - RAY
L - LINE
ESC after X/R/L - terminate current drawing
DELETE after X/R/L - delete the last drawing

The concepts are borrowed from AutoCAD.

### CODE REVIEW

**Comment by rrag** [comment]
Great!! Thanks.

There are some changes made in the `next` branch for the 0.4 I will have to review this one more time before I merge. Will do tomorrow.

nit. can you do this from separate branch on your repo and not from master.

**Comment by WaiSiuKei** [comment]
I will try to open a `hotkey` branch, and continue similar feature there.

**Comment by rrag** [comment]
PR to `next` branch if that is not too much trouble. If you face issues, go with master and I will rebase next after the merge

Looking at the code, I see there are 3 different types of lines, `XLINE` `RAY` and `LINE` and depending on the type, the start and end positions differ. How can I use these 3 types of lines without the hotkeys, but just using mouse.

It seems to me the type of line has to be a prop to the `TrendLine` and this prop can be changed by hotkeys / other ways on user land. I think all we need is 2 hotkeys

one hotkey to either start/end at the mouse position
another hotkey to start/end at the snapped position.

Thoughts?

You seemed to have a good understanding of the code even with no documentation or having discussions with me on this. Congrats, if I may could you contribute to the discussion at https://github.com/rrag/react-stockcharts/issues/44

**Comment by WaiSiuKei** [comment]
There are some conflicts between my modification and the `next` branch, and I some new idea now, so I will have a review and postpone the PR.

And as for your opnion about the `TrendLine` props and hotkeys, I'm totally agree with you.But current version of  `ReStock` has not expose much interface for my to control the `TrendLine` drawing, so I can just achieve my purpose by a hacking way.

When reading the src of `ReStock`, I think that you are doing something a little like a React + Redux SPA, you use the state of  `EventHandler` as the store, use `EventCapture` to dispatch actions and Interactive components to hold the reducer logic. The mixture of event handling the views will just make the components stateful and deviate from the trend of making stateless components, which should have a separation of the two things.

I think a most unique chart should be something like:
```
<Chart state={store} onEvent={handleEvent}>
```
the chart is totally driven by the state and every event which will cause the chart-rendering change should by pass to the `eventHandler`, chart should not response to the event itself, by provide an interface for the outside world to know the `nextState` by accroding to current state and the last event,  so an `eventHandler` will be:
```
handleEvent(event, preState) {
    ver nextState = Chart.interfaceToKnowTheNextState(event, preState)
   //then set the chart to new state
    ...
}
```

If the state could store not only the drawing entities, but also the interactive event stack, it will make the chart to be able to redo and undo, and the the interactive process could be 'replay' like a video if we reflow the state with the same time interval!

**Comment by rrag** [comment]
Added `lineType` prop to `TrendLine` which can take one of 3 values in the `next` branch

```js
	lineType: React.PropTypes.oneOf([
		"XLINE", // extends from -Infinity to +Infinity
		"RAY", // extends to +/-Infinity in one direction
		"LINE", // extends between the set bounds
	]),
```

Sorry could not merge your changes, due to lot of many conflicts. Thanks for the PR and idea.

**Pull request closed without merging**
