### PR TITLE
Added possibility  to customize OHLCTooltip texts.

### PR DESCRIPTION
**Pull request by akahan**

### CODE REVIEW

**Comment by piotryordanov** [comment]
We're working on something similar in #356 to allow you to add ur own custom children.

**Comment by rrag** [comment]
Thank you. I will review this and the other pr, and combine them

**Comment by akahan** [comment]
Ok. @piotryordanov Will be cool)

**Comment by rrag** [comment]
Sorry for the delay, There were too many conflicts, so I copied over the code to a new branch

**Pull request closed without merging**
