### PR TITLE
deleted redundant export default in lib/interactive/makeInteractive.jsx

### PR DESCRIPTION
**Pull request by ZachLiuGIS**
There's a redundant export default.

### CODE REVIEW

**Comment by rrag** [comment]
isnt this already on master>?

**Comment by timhwang21** [comment]
Master has two `export default`s -- [line 14](https://github.com/rrag/react-stockcharts/blob/master/src/lib/interactive/makeInteractive.jsx#L14), [line 204](https://github.com/rrag/react-stockcharts/blob/master/src/lib/interactive/makeInteractive.jsx#L204).

**Comment by rrag** [comment]
I thought I merged this already, seems I missed it sorry.

Just FYI, the `next` branch does not have this problem, mainly because `makeInteractive` is deleted there :)

**Comment by msanty** [comment]
Hi Ragu, could you share the code for the react-stockcharts demo?


http://rrag.github.io/stockcharts-demo/


That would be greatly appreciated!

react-stockcharts - Demo - GitHub Pages<http://rrag.github.io/stockcharts-demo/>
rrag.github.io
Choose a Chart Type, Candlestick, Line, Point & Figure and more ; Skip ? Back Next ?

Thanks,


Matthew A. Santy
404.538.7868


________________________________

**Pull request merged**
